### ISSUE TITLE
FR8: Enrolling in price target alerts

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#11]
| FR8: Enrolling in price target alerts |
|---|
| **Goal**: The system will allow users to enroll in price target alerts based on their watchlists. |
| **Stakeholders:**  End Users|
| **Description:** When a user selects their watchlist the system will display all current cryptocurrencies on their watchlist and the alerts the user has decided to receive. The user will be able to enroll in a price target SMS alerts for a specific cryptocurrency they have in their watchlist. The user must enter a specific price target for the cryptocurrency they selected. The system will then update the price target SMS alert on the watchlist and send an SMS alert to the customer when the selected cryptocurrency reaches the user specified price target. |
| **Origin:** Based on the initial project specification document, team members came up with this functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
|  **Priority:** 8 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/67
