### ISSUE TITLE
FR10: Manage alert enrollment status

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#13]
| FR10: Manage alert enrollment status |
|---|
| **Goal**: The system will allow users to manage their alert enrollment status.|
| **Stakeholders:** End Users|
| **Description:** When a user selects their watchlist the system will display all current cryptocurrencies on their watchlist, and the SMS alerts the user has selected to receive.  The system will allow the user to add and remove specific cryptocurrencies SMS alerts to and from their watchlist. Once the user makes changes to their watchlist SMS alerts, the system will update the customers watchlist SMS alerts and display the latest watchlist SMS alerts the user wishes to receive.  |
| **Origin:** Based on the initial project specification document, team members came up with this functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 | 
|  **Priority:** 10  |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/67
