### ISSUE TITLE
FR11: Search site for cryptocurrency’s statistics 

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#14]
| FR11: Search site for cryptocurrency’s statistics  |
|---|
| **Goal**: The system will allow users to search for crypto to see price and other standard pricing information|
| **Stakeholders:** End Users|
| **Description:**When a user is on the website the system will display a search box and a user can search for whatever cryptocurrency they want. When the user selects the cryptocurrency that they want to look at, the user will see the crypto’s name in the title of the page and a header along with a chart with price data. Below there will be information such as low and high price for the day, volumes, etc.  |
| **Origin:** Based on the initial project specification document, team members came up with this functional requirement description during the first planning meeting.|
| **Version:** 1.0  |  
| **Date:** 05/29/2021 | 
| **Priority:** 11 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/53
