### ISSUE TITLE
FR12: Third-party education

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#15]
| FR12: Third-party education |
|---|
| **Goal**: The website will have a selection of articles (written by third parties) that can educate users on entry level crypto information. |
| **Stakeholders:** End Users |
| **Description:** When a user is unsure of their trading decisions, they user will have multiple articles to consult regarding their issue based on known bullish/bearish flags, or any other indicators that could signify a cryptocurrency is going up or down. This will give the user more confidence with their decision |
| **Origin:** Based on the initial project specification document, team members came up with this functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 | 
| **Priority:** 12 |

**Comment by vionaveseli** [comment]
PR; https://github.com/WSU-4110/Crypto/pull/49

**Comment by vionaveseli** [comment]
Third party is only working locally because of the expired API
Bug: https://github.com/WSU-4110/Crypto/issues/76
