### ISSUE TITLE
FR13: First-party education

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#16]
| FR13: First-party education |
|---|
| **Goal**: The system will provide users basic information needed on how to trade cryptocurrencies. |
| **Stakeholders:** End Users |
| **Description:** The users will have first-party information from the developers to make it easier to find information, rather than having to look for articles and search. Basics such as what platform to use for trading, short-term and long-term positives, and negatives, etc.  |
| **Origin:** Based on the initial project specification document, team members came up with this functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |  
| **Priority:**  13|

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/26
