### ISSUE TITLE
FR14: Cryptocurrency Price Chart

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#17]
| FR14: Cryptocurrency Price Chart |
|---|
| **Goal**: The system will provide users graph of price history for specific cryptocurrencies. |
| **Stakeholders:** End Users|
| **Description:** The system will allow users to select a coin and see its price chart in USD. The system will allow display the live price of the coin.  |
| **Origin:** Team members came up with this functional requirement description during the 07/13/2021 meeting. |
| **Version:** 1.1  |  
| **Date:** 07/13/2021 |
| **Priority:** 14  |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/62
