### ISSUE TITLE
FR15: Cryptocurrency Statistics

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#18]
| FR15: Cryptocurrency Statistics |
|---|
| **Goal**: The system will allow a user to see the period high, low, and other relevant pricing information.|
| **Stakeholders:** End Users|
| **Description:** The system will provide users a useful tool that every crypto information app has. The tool will provide information like price range, average price within a period, volume, market cap, and other statistics of the crypto.  |
| **Origin:** Based on the initial project specification document, team members came up with this functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
| **Priority:** 15 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/53
