### ISSUE TITLE
NR1:  Security - Encrypt User Data

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#19]
| NR1: Security - Encrypt User Data |
|---|
| **Goal**: A user’s (Personally Identifiable Information) PII will be encrypted within the user database. This includes passwords. Users include end-users as well as developers who will authenticate with the website. |
| **Stakeholders:** All (End Users & Developers) |
| **Description:** When a user enters the website they will have the option to create an account. An account will be required to perform actions such as creating watchlists, alerts, etc. The user’s credentials will be stored in a database. We will ensure that this database is secure and that the user’s information is protected and inaccessible to the public. |
| **Origin:** Based on the initial project specification document, team members came up with this non-functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
| **Priority:** 1 |

**Comment by IKwiotek** [comment]
Because we utilized Firebase authentication, we were provided the following features:
- Firebase Authentication automatically provides password hashing. 
- An internally modified script is used to hash account passwords.
- These passwords are not visible to the developers through the Firebase application page, further protecting the end-users.


Details for Firebase Authentication hashing may be found at: https://firebaseopensource.com/projects/firebase/scrypt/

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/25
