### ISSUE TITLE
NR2: Privacy - Privacy Agreement

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#20]
| NR2: Privacy - Privacy Agreement |
|---|
| **Goal**: Users will have access to a security policy from the homepage. We will state how user information is shared with third parties. |
| **Stakeholders:** End Users |
| **Description:**  When a user enters the website they will have an option to navigate to a page that outlines the product’s security policy. This policy will include how user data is used, if it is shared with any third parties, and possibly some information regarding how their data is also secured and encrypted (Outlined in NR1). |
| **Origin:** Based on the initial project specification document, team members came up with this non-functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
| **Priority:** 5 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/60
