### ISSUE TITLE
NR3: Usability - FAQ User Documentation

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#21]
| NR3: Usability - FAQ User Documentation |
|---|
| **Goal**: Users will have access to a FAQ section from the homepage. The FAQ section will guide users through how to use the website. |
| **Stakeholders:** End Users |
| **Description:** When a user enters the website they will have an option to navigate to a page that outlines the product’s FAQ / User Documentation. This documentation will include basic user information such as creating an account, performing basic actions, and possibly some information regarding upcoming features. This page will allow new users to obtain an understanding of how to use the website quickly and easily.  |
| **Origin:** Based on the initial project specification document, team members came up with this non-functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
| **Priority:** 3 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/39
