### ISSUE TITLE
NR4: Availability - Determine Hosting Platform & Deployment Strategy with High Availability

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#22]
| NR4: Availability - Determine Hosting Platform & Deployment Strategy with High Availability |
|---|
| **Goal**: Choosing a reliable hosting platform and determining a production deployment strategy that minimizes downtime will allow for high availability. End users will be notified of planned deployments within the website. |
| **Stakeholders:** All (End Users & Developers) |
| **Description:** The system will provide a reliable hosting infrastructure so users will be able to view pages and resources with minimal lag and high availability at different times of day. |
| **Origin:** Based on the initial project specification document, team members came up with this non-functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
| **Priority:** 2 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/42
