### ISSUE TITLE
NR5: Performance - User interaction errors will be kept to a minimum.

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#23]
| NR5: Performance - User interaction errors will be kept to a minimum. |
|---|
| **Goal**: HTTP Errors of classes 400 and 500 will be minimized for users wherever possible. HTTP links that do not resolve, errors in saving user inputs, etc will be kept to a minimum. |
| **Stakeholders:**  All (End Users & Developers) |
| **Description:** The system will provide our end users with a smooth browsing experience. In order to do this, the system will suppress 400 and 500 errors while still telling the users they have an error. |
| **Origin:** Based on the initial project specification document, team members came up with this non-functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
| **Priority:** 4 |

**Comment by vionaveseli** [comment]
We tested the website thoroughly to make sure there were no user errors. Every form's inputs and buttons have been positive and negative tested. There are no HTTP errors. The site has exception handling wherever a user has to input anything. We also deployed each change to ensure no errors were created during any changes.
