### ISSUE TITLE
FR16: Password Reset Guidance

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#28]
| FR16: Password Reset Guidance |
|---|
| **Goal**: Users will have access to reset their password from the login page. Ideally, users will also be able to reset their password from their Profile. |
| **Stakeholders:** End Users |
| **Description:**  When a user enters the website they will be required to authenticate. If a user is unable to remember their password, they will have the option to reset their password from the Login page. Additionally, users will be able to reset their password from within their Profile. |
| **Origin:** Based on the initial project specification document, team members came up with this non-functional requirement description during the second planning meeting. |
| **Version:** 1.0  |  
| **Date:** 06/22/2021 |
| **Priority:** 16 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/25

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/38
