### ISSUE TITLE
FR17: Manage User Profile

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#29]
| FR17: Create and Manage User Profile |
|---|
| **Goal**: Users will have access to a Profile from the homepage when they register. The user profile will centralize all user settings such as alert configurations and watchlist. Users will need to be able to manage their profile. |
| **Stakeholders:** End Users |
| **Description:**  When a user enters the website they will have an option to navigate to a profile page. The profile page will be used to manage each user's settings, including price alerts, whale alerts, and watchlists. This page could also be used to house additional user-centric functionality. |
| **Origin:** Based on the initial project specification document, team members came up with this non-functional requirement description during the second planning meeting. |
| **Version:** 1.0  |  
| **Date:** 06/22/2021 |
| **Priority:** 17 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/48

PR: https://github.com/WSU-4110/Crypto/pull/46

PR: https://github.com/WSU-4110/Crypto/pull/42
