### ISSUE TITLE
FR18: Create Alert Mechanism

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#30]
| FR18: Create Alert Mechanism |
|---|
| **Goal**: This issue will serve to create the basis of the alerting functionality used by both the Price Alerts and the Whale Alerts. |
| **Stakeholders:** End Users |
| **Description:**  When a user enters the website they will have an option to navigate to a profile page. From within the Profile page, the user will be able to opt-in to Price Alerts and Whale Transaction alerts. |
| **Origin:** Based on the initial project specification document, team members came up with this non-functional requirement description during the second planning meeting. |
| **Version:** 1.0  |  
| **Date:** 06/22/2021 |
| **Priority:** 18 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/67
