### ISSUE TITLE
FR1: User Registration

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#4]
| FR1: User Registration |
| --- |
| **Goal**: When entering the website, users will have the option to create an account within the website. |
| **Stakeholders:** End Users |
| **Description:** Once a user enters the website, the system gives the user the option to create an account with a username and password. These credentials will save an account on the website for that designated user.  |
| **Origin:** Based on the initial project specification document, team members came up with this functional requirement description during the first planning meeting.  |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
| **Priority:** 1  |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/25
