### ISSUE TITLE
FR2: User Authentication

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#5]
| FR2: User Authentication |
| --- |
| **Goal**: A user will be able to access an account by logging into the website with a predetermined username and password.|
| **Stakeholders:** End Users |
| **Description:** After a user creates an account with a username and password, the system will allow the user to access said account by using the username and password in order to log in. If a user cannot remember their login credentials, the system will show a forgot password button in order to allow the user to reset their password. |
| **Origin:** Based on the initial project specification document, team members came up with this functional requirement description during the first planning meeting.|
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
| **Priority:** 2 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/25
