### ISSUE TITLE
FR3: Email Signup

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#6]
| FR3: Email Signup |
| --- |
| **Goal**: The system will allow users to use an email in order to sign up for emails from the website. |
| **Stakeholders:** End Users |
| **Description:** When on the website, the system will provide users an option to enroll into an email distribution group by either providing an email or allowing the email of their account to be added to the email list.  |
| **Origin:** 07/13/2021 meeting |
| **Version:** 2.0  |  
| **Date:** 07/13/2021 |
| **Priority:**  3|

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/48
