### ISSUE TITLE
FR4: Manage Email Enrollment Status

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#7]
| FR4: Manage Email Enrollment Status |
|---|
| **Goal**: The system will allow users to choose whether they want to receive emails from the site and will have the options to subscribe or unsubscribe.  |
| **Stakeholders:** End Users  |
| **Description:** The system will allow users to manage their email enrollment status to their liking in terms of getting emails from the site. If users decide they do not wish to receive them, they will have the option to unsubscribe.  |
| **Origin:** Based on the initial project specification document, team members came up with this functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
| **Priority:** 4 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/48
