### ISSUE TITLE
FR5: System update notifications

### ISSUE THREAD

**Issue by IKwiotek** [WSU-4110/Crypto#8]
|FR5: System update notifications|
|---|
| **Goal**:The system will allow users to be aware of any changes or updates that occur on the system.  |
| **Stakeholders:** End Users |
| **Description:** The system will allow users to be notified of news and changes that happen within our system. Users will be kept up to date with changes that occur within the system.  |
| **Origin:** Based on the initial project specification document, team members came up with this functional requirement description during the first planning meeting. |
| **Version:** 1.0  |  
| **Date:** 05/29/2021 |
|  **Priority:** 5 |

**Comment by vionaveseli** [comment]
PR: https://github.com/WSU-4110/Crypto/pull/59
